version: "3.8"
services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isilinda
      POSTGRES_DB: dbpayroll
    ports:
      - "5432:5432"
  app:
    container_name: tingeso_docker_1
    image: isisi/tingeso_docker_1
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dbpayroll?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=isilinda
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db

