version: "3.8"
services:


  nginx-backend:
    image: nginx
    container_name: nginx-backend
    restart: always
    ports:
      - "80:80"
    networks:
      - tingeso_network
    volumes:
      - ./backend_tingeso.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3


  nginx-frontend:
    image: nginx
    container_name: nginx-frontend
    restart: always
    ports:
      - 8070:8070
    networks:
      - docker_tingeso_frontend-network 
    volumes:
      - ./frontend_tingeso.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend_tingeso1
      - frontend_tingeso2
      - frontend_tingeso3


  postgres-db:
    container_name: postgres
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - dbpayroll:/var/lib/postgresql/data
    networks:
      - tingeso_network
    environment:
      POSTGRES_PASSWORD: isilinda
      POSTGRES_DB: dbpayroll
    ports:
      - "5432:5432"


  app1:
    container_name: tingeso_docker_11
    image: isisi/tingeso_docker_1:latest
    ports:
      - "8091:8090"
    networks:
      - tingeso_network
    environment:
      - DB_HOST = localhost 
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dbpayroll?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=isilinda
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db


  app2:
    container_name: tingeso_docker_2
    image: isisi/tingeso_docker_1:latest
    ports:
      - "8092:8090"
    networks:
      - tingeso_network     
    environment:
      - DB_HOST = localhost 
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dbpayroll?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=isilinda
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db

  app3:
    container_name: tingeso_docker_3
    image: isisi/tingeso_docker_1:latest
    ports:
      - "8093:8090"
    networks:
      - tingeso_network      
    environment:
      - DB_HOST = localhost 
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dbpayroll?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=isilinda
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db



  frontend_tingeso1:
    container_name: docker_tingeso_frontend1
    image: isisi/tingeso_docker_frontend:latest
    ports:
      - 3001:3000
    networks:
      - docker_tingeso_frontend-network
    deploy:
      restart_policy:
        condition: on-failure

  frontend_tingeso2:
    container_name: docker_tingeso_frontend2
    image: isisi/tingeso_docker_frontend:latest
    ports:
      - 3002:3000
    networks:
      - docker_tingeso_frontend-network   
    deploy:
      restart_policy:
        condition: on-failure

  frontend_tingeso3:
    container_name: docker_tingeso_frontend3
    image: isisi/tingeso_docker_frontend:latest
    ports:
      - 3003:3000
    networks:
      - docker_tingeso_frontend-network 
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  dbpayroll:

networks:
  tingeso_network:
  docker_tingeso_frontend-network:

